### PR TITLE
Pass MAC address from uboot to kernel, makes netboot over NFS work properly

### PR DESCRIPTION
**Pull request by neiser**
This patch makes uboot netbooting work for my system, hooray! 
Before that, the kernel driver smsc95xx could not determine the MAC address of the RPI, altough u-boot already knew the correct one. So I implemented the same behaviour as presumably start.elf does when directly booting kernels, i.e. appending something like "smsc95xx.macaddr=B8:27:EB:59:EB:25" to the kernel command line, see here: http://www.raspberrypi.org/forums/viewtopic.php?t=33252

I implemented first the feature that cmd_pxe does not simply overwrite the bootargs environment variable, but prepends the contents if bootargs is already set. Then I changed the pxe boot script to set bootargs to smsc95xx.macaddr=${usbethaddr}

I tested it here, and it works, but I don't know if this is really the proper way to fix it. Comments welcome!

### CODE REVIEW

**Comment by swarren** [comment]
I'm starting to think about the best way to handle this. However, I don't see any code in the mainline kernel that actually handles the smsc95xx.macaddr command-line. Do you also have a kernel patch that implements this? If so, have you attempted to upstream that yet?

**Comment by neiser** [comment]
It may be that only the RPi people honor this smsc95xx.macaddr line. I have not checked this, I was just trying to mimick the RPi bootloader in this matter (and actually make my NFS boot work properly).
Maybe the best solution would be if the smsc95xx was able to read the MAC address as uboot does? What do you think? This could then be pushed to the upstream kernel.

**Comment by ali1234** [comment]
In later kernels this is handled with device tree. The broadcom firmware loads the device tree blob from the fat partition and makes some changes in it. It will only do this if an appropriate dtb file exists on the sd card (filename is hardcoded into the firmware) and also the kernel (or u-boot image) you ask it to load is tagged as supporting device tree with mkknlimg. It loads the fdt at 0x100. To see the changes made by the firmware you can dump the fdt to plain text with "fdt print /", then reload the original blob from the fat partition, and then redump it. Then simply diff the two outputs. That produces an output like this:

```
1a2
>   memreserve = <0x3b000000 0x04000000>;
6a8,37
>   display {
>       broadcom,depth = <0x00000010>;
>       broadcom,height = <0x00000000>;
>       broadcom,width = <0x00000000>;
>   };
>   system {
>       linux,serial = <0x00000000 0x3c5da33a>;
>       linux,revision = <0x00a01041>;
>   };
>   axi {
>       uart0 {
>           clock-frequency = <0x002dc6c0>;
>       };
>       sdhci {
>           clock-frequency = <0x0ee6b280>;
>       };
>       dma {
>           broadcom,channels = <0x00007f35>;
>       };
>       usb {
>           hub {
>               ethernet {
>                   mac-address = [b8 27 eb 5d a3 3a];
>               };
>           };
>       };
>       vc_mem {
>           reg = <0x3dc00000 0x3f000000 0xc0000000>;
>       };
>   };
8c39
<       bootargs = "";
---
>       bootargs = "dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2709.boardrev=0xa01041 bcm2709.serial=0x3c5da33a smsc95xx.macaddr=B8:27:EB:5D:A3:3A bcm2708_fb.fbswap=1 bcm2709.disk_led_gpio=47 bcm2709.disk_led_active_low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 elevator=deadline root=/dev/mmcblk0p2 rootfstype=ext4 rootwait";
37c68
<       reg = <0x00000000 0x00000000>;
---
>       reg = <0x00000000 0x3b000000>;
60c91
<           interrupts = * 0x0000062c [0x00000060];
---
>           interrupts = * 0x00000954 [0x00000060];
403c434
<       arm_freq = * 0x00001d94 [0x00000058];
---
>       arm_freq = * 0x000020bc [0x00000058];
440c471
<           clock-frequency = <0x2faf0800>;
---
>           clock-frequency = "5��";
448c479
<           clock-frequency = <0x2faf0800>;
---
>           clock-frequency = "5��";
456c487
<           clock-frequency = <0x2faf0800>;
---
>           clock-frequency = "5��";
464c495
<           clock-frequency = <0x2faf0800>;
---
>           clock-frequency = "5��";
```

u-boot already seems to contain routines for manipulating the values in device tree so it should be possible to extract the appropriate MAC and serial numbers from memory and then reinsert them into a new fdt file you loaded with u-boot. I haven't tried it yet though.

**Comment by swarren** [comment]
The bindings involved there are not upstream AFAIK. If/when they are, U-Boot could be easily modified to support them.

**Comment by msmuenchen** [comment]
I have published a patchset for passing through the devicetree and cmdline from start.elf to a Linux guest: http://lists.denx.de/pipermail/u-boot/2015-November/235879.html

@swarren sent you a mail with the full patchsets I did

**Comment by swarren** [comment]
Closing this pull request since any patches should be sent on the mailing lists for inclusion in mainline U-Boot, rather than just in my personal development repository.

**Comment by swarren** [comment]
FYI, see here for some upstream activity that proposes a standard way to do this:
http://www.spinics.net/lists/kernel/msg2179104.html
[PATCH 0/2] Set the Raspberry Pi Ethernet MAC address

**Pull request closed without merging**
